spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/token_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    discovery:
      enabled: false
  kafka:
    listener:
      auto-startup: false

server:
  address: ${SERVER_ADDRESS:127.0.0.1}
  port: ${SERVER_PORT:8084}

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

token:
  kafka:
    consumer-enabled: false
  outbox:
    enabled: false
  mock:
    enabled: true
    member-uuid: aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa
  charge:
    reconcile:
      enabled: false

portone:
  stub-enabled: false
  store-id: store-e091eba1-ca0f-4fa7-8134-0fe43e9e727e
  channel-key: channel-key-37faef63-c3a7-435f-afa1-b4dd0421860f
  api-secret: LNHflrDOCq7DYbmKUjFzVih7vj121xQdEbfBUW6FDF078hP7OSSLI6bOHzRmrb5yoNtzWdHHG0b8YUC4
  api-base-url: https://api.portone.io

# powershell 실행 방법
# cd 'C:\Users\G07\Desktop\plan&with_DB\planwith_fo_token'

# $env:SPRING_PROFILES_ACTIVE='local'

# java -classpath '.\gradle\wrapper\gradle-wrapper.jar' org.gradle.wrapper.GradleWrapperMain bootRun

# http://localhost:8084/swagger-ui/index.html